/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as DashboardUpgradeIndexRouteImport } from './routes/dashboard/upgrade/index'
import { Route as DashboardMeetingsIndexRouteImport } from './routes/dashboard/meetings/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/dashboard/agents/index'
import { Route as DashboardoverviewIndexRouteImport } from './routes/dashboard/(overview)/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const DashboardUpgradeIndexRoute = DashboardUpgradeIndexRouteImport.update({
  id: '/upgrade/',
  path: '/upgrade/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMeetingsIndexRoute = DashboardMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardoverviewIndexRoute = DashboardoverviewIndexRouteImport.update({
  id: '/(overview)/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/dashboard/': typeof DashboardoverviewIndexRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/dashboard/meetings/': typeof DashboardMeetingsIndexRoute
  '/dashboard/upgrade/': typeof DashboardUpgradeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/dashboard': typeof DashboardoverviewIndexRoute
  '/dashboard/agents': typeof DashboardAgentsIndexRoute
  '/dashboard/meetings': typeof DashboardMeetingsIndexRoute
  '/dashboard/upgrade': typeof DashboardUpgradeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(marketing)/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/dashboard/(overview)/': typeof DashboardoverviewIndexRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/dashboard/meetings/': typeof DashboardMeetingsIndexRoute
  '/dashboard/upgrade/': typeof DashboardUpgradeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/'
    | '/dashboard/agents/'
    | '/dashboard/meetings/'
    | '/dashboard/upgrade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/dashboard/agents'
    | '/dashboard/meetings'
    | '/dashboard/upgrade'
  id:
    | '__root__'
    | '/(auth)'
    | '/(marketing)'
    | '/dashboard'
    | '/(marketing)/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/dashboard/(overview)/'
    | '/dashboard/agents/'
    | '/dashboard/meetings/'
    | '/dashboard/upgrade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/dashboard/upgrade/': {
      id: '/dashboard/upgrade/'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade/'
      preLoaderRoute: typeof DashboardUpgradeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/meetings/': {
      id: '/dashboard/meetings/'
      path: '/meetings'
      fullPath: '/dashboard/meetings/'
      preLoaderRoute: typeof DashboardMeetingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/agents/': {
      id: '/dashboard/agents/'
      path: '/agents'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(overview)/': {
      id: '/dashboard/(overview)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardoverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardoverviewIndexRoute: typeof DashboardoverviewIndexRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
  DashboardMeetingsIndexRoute: typeof DashboardMeetingsIndexRoute
  DashboardUpgradeIndexRoute: typeof DashboardUpgradeIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardoverviewIndexRoute: DashboardoverviewIndexRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
  DashboardMeetingsIndexRoute: DashboardMeetingsIndexRoute,
  DashboardUpgradeIndexRoute: DashboardUpgradeIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  marketingRouteRoute: marketingRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
